import fs from 'node:fs/promises';
import path from 'node:path';

export const GENERATED_HEADER = '<!-- Generated by futaba-context. -->';
const START = '<!-- futaba:start -->';
const END = '<!-- futaba:end -->';

export async function listMarkdownFiles(directory, { excludeReadme = false } = {}) {
  let entries;
  try {
    entries = await fs.readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error.code === 'ENOENT') return [];
    throw error;
  }

  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .filter((entry) => !excludeReadme || entry.name.toLowerCase() !== 'readme.md')
    .map((entry) => path.join(directory, entry.name))
    .sort();
}

export async function readCombinedMarkdown(directory) {
  const files = await listMarkdownFiles(directory, { excludeReadme: true });
  const sections = await Promise.all(files.map((file) => fs.readFile(file, 'utf8')));
  return sections.map((section) => section.trim()).filter(Boolean).join('\n\n');
}

export async function writeManagedMarkdown(file, title, content) {
  const block = `${START}\n${GENERATED_HEADER}\n\n# ${title}\n\n${content.trim()}\n${END}`;
  await fs.mkdir(path.dirname(file), { recursive: true });

  let existing = '';
  try {
    existing = await fs.readFile(file, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }

  const start = existing.indexOf(START);
  const end = existing.indexOf(END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    throw new Error(`invalid Futaba managed block in ${file}`);
  }

  const output = start === -1
    ? [existing.trimEnd(), block].filter(Boolean).join('\n\n')
    : `${existing.slice(0, start)}${block}${existing.slice(end + END.length)}`;

  await fs.writeFile(file, `${output.trimEnd()}\n`);
}

export async function copySkills(source, destination) {
  await fs.mkdir(destination, { recursive: true });
  let entries;
  try {
    entries = await fs.readdir(source, { withFileTypes: true });
  } catch (error) {
    if (error.code === 'ENOENT') return [];
    throw error;
  }

  const copied = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillSource = path.join(source, entry.name);
    const skillFile = path.join(skillSource, 'SKILL.md');
    try {
      await fs.access(skillFile);
    } catch {
      continue;
    }

    const skillDestination = path.join(destination, entry.name);
    const destinationSkill = path.join(skillDestination, 'SKILL.md');
    try {
      const existing = await fs.readFile(destinationSkill, 'utf8');
      if (!existing.includes(GENERATED_HEADER)) {
        throw new Error(`refusing to overwrite project-owned skill: ${destinationSkill}`);
      }
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }

    await fs.mkdir(skillDestination, { recursive: true });
    await fs.cp(skillSource, skillDestination, { recursive: true, force: true });
    const content = await fs.readFile(destinationSkill, 'utf8');
    await fs.writeFile(destinationSkill, `${GENERATED_HEADER}\n${content}`);
    copied.push(destinationSkill);
  }
  return copied;
}

export async function copyAgentDefinitions(source, destination) {
  const files = await listMarkdownFiles(source, { excludeReadme: true });
  const copied = [];
  await fs.mkdir(destination, { recursive: true });
  for (const file of files) {
    const target = path.join(destination, path.basename(file));
    try {
      const existing = await fs.readFile(target, 'utf8');
      if (!existing.includes(GENERATED_HEADER)) {
        throw new Error(`refusing to overwrite project-owned agent definition: ${target}`);
      }
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    const content = await fs.readFile(file, 'utf8');
    await fs.writeFile(target, `${GENERATED_HEADER}\n${content}`);
    copied.push(target);
  }
  return copied;
}
